"""Coins migration.

Revision ID: ee4c72469e22
Revises: edc4212f8e5b
Create Date: 2024-07-20 15:10:45.066441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4c72469e22'
down_revision = 'edc4212f8e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('referral_user_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('user')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('coins')

    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('referral_user_fkey', 'user', ['user'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
