"""Reward migration.

Revision ID: 274cb55fcbaa
Revises: 743fb2ca89cb
Create Date: 2024-07-24 15:29:11.573311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274cb55fcbaa'
down_revision = '743fb2ca89cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_given', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.drop_column('reward_given')

    # ### end Alembic commands ###
