"""Reward migration.

Revision ID: b007ae530844
Revises: 274cb55fcbaa
Create Date: 2024-07-24 16:01:02.622293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b007ae530844'
down_revision = '274cb55fcbaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.drop_constraint('referral_code_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.create_unique_constraint('referral_code_key', ['code'])

    # ### end Alembic commands ###
